# Generated by Django 3.0.5 on 2020-04-10 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talpynroot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, verbose_name='Course')),
                ('description', models.TextField(blank=True)),
                ('old_price', models.PositiveIntegerField()),
                ('new_price', models.PositiveIntegerField()),
                ('date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=100, verbose_name='Lesson')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talpynroot.Course')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(default='Almaty', max_length=100, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='course',
            field=models.CharField(default='Kazakhstan', max_length=100, verbose_name='Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(default='8708', max_length=100, verbose_name='Phone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='sex',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=100, verbose_name='Course')),
                ('url', models.CharField(max_length=225, verbose_name='Video')),
                ('time', models.DurationField()),
                ('desctiprion', models.TextField(blank=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talpynroot.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=30, unique=True, verbose_name='Course')),
                ('recerved', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talpynroot.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Opinion')),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talpynroot.Client')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talpynroot.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Opinion')),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talpynroot.Comment')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talpynroot.Course')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='courses',
            field=models.ManyToManyField(to='talpynroot.Course'),
        ),
    ]
