# Generated by Django 3.0.5 on 2020-04-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talpynroot', '0002_auto_20200410_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
