# Generated by Django 2.2.6 on 2020-04-08 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talpynroot', '0002_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
