# Generated by Django 2.2.6 on 2020-04-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talpynroot', '0003_auto_20200410_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tokens',
            field=models.PositiveIntegerField(choices=[(50, '50'), (100, '100'), (200, '200'), (500, '500'), (1000, '1000')], default=50),
        ),
    ]
