# Generated by Django 2.2.6 on 2020-04-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talpynroot', '0004_course_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=50, unique=True, verbose_name='Course'),
        ),
    ]
